#!/bin/bash
set -euo pipefail

# Check for root
if [ "$EUID" -ne 0 ]; then echo "Run as root."; exit 1; fi

# Install dependencies
if ! command -v upnpc &> /dev/null; then
    apt-get update -qq && apt-get install -y -qq miniupnpc cron
fi

KEEPALIVE="/usr/local/bin/upnp-keepalive.sh"

# Initialize keepalive script with header
cat > "$KEEPALIVE" << 'EOF'
#!/bin/bash
# UPnP port mappings keepalive script
# Auto-generated by add-persistent-upnp.sh

EOF
chmod +x "$KEEPALIVE"

# Setup cron job
if ! crontab -l 2>/dev/null | grep -Fq "$KEEPALIVE"; then
    (crontab -l 2>/dev/null; echo "@hourly $KEEPALIVE 2>&1 | logger -t upnp-keepalive") | crontab -
    echo "✓ Cron job installed"
fi

# Show current mappings
echo "Current UPnP mappings:"
upnpc -l 2>/dev/null | grep -E '^\s*[0-9]+\s' || echo "None"
echo

echo "Add port forwarding rules (press Enter on empty port to finish)"
count=0

while true; do
    read -rp "Port: " port
    [ -z "$port" ] && break
    
    read -rp "Protocol (TCP/UDP) [TCP]: " proto
    proto=$(echo "${proto:-TCP}" | tr '[:lower:]' '[:upper:]')
    
    if upnpc -e "UPnP-$port" -r "$port" "$proto" &> /dev/null; then
        echo "✓ Mapped $port/$proto"
        echo "upnpc -e 'UPnP-$port' -r $port $proto &> /dev/null" >> "$KEEPALIVE"
        ((count++))
    else
        echo "✗ Failed to map $port/$proto"
    fi
done

[ "$count" -gt 0 ] && echo -e "\n✓ Added $count port mapping(s)" || echo "No ports added"
